# Generated by Django 3.1.6 on 2021-03-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='items',
            field=models.JSONField(default=list, max_length=10000),
        ),
    ]
