# Generated by Django 3.1.6 on 2021-03-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_likes',
            field=models.JSONField(default=dict),
        ),
    ]
