# Generated by Django 3.1.6 on 2021-04-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.URLField(default=''),
        ),
    ]
