# Generated by Django 3.1.6 on 2021-03-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalserver',
            name='id',
        ),
        migrations.AlterField(
            model_name='externalserver',
            name='host',
            field=models.URLField(default='', primary_key=True, serialize=False),
        ),
    ]
