# Generated by Django 3.1.6 on 2021-03-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.JSONField(default=dict),
        ),
    ]
