# Generated by Django 3.1.7 on 2021-03-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], max_length=10),
        ),
    ]
