# Generated by Django 3.1.6 on 2021-02-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id',
            new_name='uid',
        ),
    ]
