# Generated by Django 3.1.6 on 2021-03-27 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='Like', max_length=10)),
                ('context', models.URLField(default='')),
                ('summary', models.TextField(default='')),
                ('author', models.JSONField(default=dict)),
                ('object', models.URLField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='LikeSingle',
        ),
    ]
