# Generated by Django 3.1.6 on 2021-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False # **<<< HERE**

    dependencies = [
        ('Iconicity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='uid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='externalFollows',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='actor',
            field=models.JSONField(default=dict, max_length=500),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='object',
            field=models.JSONField(default=dict, max_length=500),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='type',
            field=models.CharField(default='follow', max_length=10),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='items',
            field=models.JSONField(default=list, max_length=10000),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(default='like', max_length=10),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follow',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.JSONField(default=dict, max_length=500),
        ),
    ]
