# Generated by Django 3.1.6 on 2021-03-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0002_post_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
