# Generated by Django 3.1.6 on 2021-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0002_auto_20210220_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.JSONField(default=dict),
        ),
    ]
