# Generated by Django 3.1.6 on 2021-03-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0002_post_external_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.URLField(default=''),
        ),
    ]
