# Generated by Django 3.1.6 on 2021-03-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0002_auto_20210330_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='uid',
            new_name='id',
        ),
    ]
