# Generated by Django 3.1.6 on 2021-03-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0003_auto_20210331_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='externalFollows',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follow',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.JSONField(default=dict, max_length=5000),
        ),
    ]
