# Generated by Django 3.1.6 on 2021-02-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0003_auto_20210220_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.JSONField(default=dict),
        ),
    ]
