# Generated by Django 3.1.6 on 2021-03-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconicity', '0004_userprofile_externalfollows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='externalFollows',
            field=models.JSONField(default=list),
        ),
    ]
